version: "3.1"
services:
  psychologist-bot:
    image: psychologist-bot
    links:
        - db:db
    volumes:
        - ../:/projects/how-r-u
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  web-interface:
    image: web_interface
    links:
        - db:db
    volumes:
      - ..:/projects/how-r-u
    ports:
      - "5000:5000"
    depends_on:
      - proxy
      - db
    restart: always

  proxy:
    image: nginx:latest
    volumes:
      - ./proxy:/etc/nginx/conf.d
      - ../web_interface/core/static/:/var/www/static/
    ports:
      - "8000:80"
    restart: always


